### PR TITLE
Support LightGBM continue training

### PR DESCRIPTION
**Pull request by terrytangyuan**
Support LightGBM continue training from a previously trained model.

### CODE REVIEW

**Comment by mhamilton723** [comment]
@terrytangyuan please feel free to tag me or email when you need a build queued!

**Comment by mhamilton723** [comment]
This resulted in a segfault:

```
2018-08-23T15:07:23.7827036Z [LightGBM] [Info] Start training from score 6.932177
2018-08-23T15:07:23.7841602Z [LightGBM] [Info] Start training from score 6.932177
2018-08-23T15:07:23.7856155Z [LightGBM] [Info] Start training from score 6.932177
2018-08-23T15:07:24.4240676Z /home/eli/agent/_work/6/s/tools/pytests/shared.sh: line 4: 130311 Aborted                 (core dumped) TEST_RESULTS="$TEST_RESULTS" "$TOOLSDIR/bin/mml-exec" spark-submit "$@" 2> "$tmperr"
2018-08-23T15:07:24.4260948Z Standard error for the above failure:
2018-08-23T15:07:24.4279583Z   | file:/home/eli/agent/_work/6/s/BuildArtifacts/packages/m2 added as a remote repository with the name: repo-1
2018-08-23T15:07:24.4303242Z   | https://mmlspark.azureedge.net/maven added as a remote repository with the name: repo-2
2018-08-23T15:07:24.4321734Z   | Ivy Default Cache set to: /home/eli/.ivy2/cache
2018-08-23T15:07:24.4336353Z   | The jars for the packages stored in: /home/eli/.ivy2/jars
2018-08-23T15:07:24.4358393Z   | :: loading settings :: url = jar:file:/home/eli/lib/spark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
2018-08-23T15:07:24.4377436Z   | com.microsoft.ml.spark#mmlspark_2.11 added as a dependency
2018-08-23T15:07:24.4395846Z   | :: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
2018-08-23T15:07:24.4413948Z   | confs: [default]
2018-08-23T15:07:24.4432267Z   | found com.microsoft.ml.spark#mmlspark_2.11;0.13.dev25+1.gbb15056 in repo-1
2018-08-23T15:07:24.4453748Z   | found io.spray#spray-json_2.11;1.3.2 in user-list
2018-08-23T15:07:24.4475005Z   | found com.microsoft.cntk#cntk;2.4 in user-list
2018-08-23T15:07:24.4495993Z   | found org.openpnp#opencv;3.2.0-1 in user-list
2018-08-23T15:07:24.4522180Z   | found com.microsoft.ml.lightgbm#lightgbmlib;2.1.200 in user-list
2018-08-23T15:07:24.4540575Z   | :: resolution report :: resolve 313ms :: artifacts dl 11ms
2018-08-23T15:07:24.4555063Z   | :: modules in use:
2018-08-23T15:07:24.4572884Z   | com.microsoft.cntk#cntk;2.4 from user-list in [default]
2018-08-23T15:07:24.4594565Z   | com.microsoft.ml.lightgbm#lightgbmlib;2.1.200 from user-list in [default]
2018-08-23T15:07:24.4616440Z   | com.microsoft.ml.spark#mmlspark_2.11;0.13.dev25+1.gbb15056 from repo-1 in [default]
2018-08-23T15:07:24.4638337Z   | io.spray#spray-json_2.11;1.3.2 from user-list in [default]
2018-08-23T15:07:24.4659802Z   | org.openpnp#opencv;3.2.0-1 from user-list in [default]
2018-08-23T15:07:24.4685915Z   | ---------------------------------------------------------------------
2018-08-23T15:07:24.4704275Z   | |                  |            modules            ||   artifacts   |
2018-08-23T15:07:24.4719025Z   | |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
2018-08-23T15:07:24.4737187Z   | ---------------------------------------------------------------------
2018-08-23T15:07:24.4755518Z   | |      default     |   5   |   0   |   0   |   0   ||   5   |   0   |
2018-08-23T15:07:24.4773700Z   | ---------------------------------------------------------------------
2018-08-23T15:07:24.4795381Z   | :: retrieving :: org.apache.spark#spark-submit-parent
2018-08-23T15:07:24.4813137Z   | confs: [default]
2018-08-23T15:07:24.4829070Z   | 0 artifacts copied, 5 already retrieved (0kB/8ms)
2018-08-23T15:07:24.4844296Z   | [LightGBM] [Fatal] Check failed: cnt_leaf_data > 0 at /home/ilya/LightGBM/src/treelearner/serial_tree_learner.cpp, line 791 .
2018-08-23T15:07:24.4859356Z   | 
2018-08-23T15:07:24.4874094Z   | [LightGBM] [Fatal] Check failed: cnt_leaf_data > 0 at /home/ilya/LightGBM/src/treelearner/serial_tree_learner.cpp, line 791 .
2018-08-23T15:07:24.4888967Z   | 
2018-08-23T15:07:24.4903846Z   | [LightGBM] [Fatal] Check failed: cnt_leaf_data > 0 at /home/ilya/LightGBM/src/treelearner/serial_tree_learner.cpp, line 791 .
2018-08-23T15:07:24.4919067Z   | 
2018-08-23T15:07:24.4933818Z   | [LightGBM] [Fatal] Check failed: cnt_leaf_data > 0 at /home/ilya/LightGBM/src/treelearner/serial_tree_learner.cpp, line 791 .
2018-08-23T15:07:24.4948885Z   | 
2018-08-23T15:07:24.4966741Z   | terminate called after throwing an instance of 'std::runtime_error'
2018-08-23T15:07:24.4985079Z   | terminate called recursively
2018-08-23T15:07:24.5001626Z   | terminate called recursively
2018-08-23T15:07:24.5015996Z   | terminate called recursively
2018-08-23T15:07:24.5031180Z   | what():  Check failed: cnt_leaf_data > 0 at /home/ilya/LightGBM/src/treelearner/serial_tree_learner.cpp, line 791 .
2018-08-23T15:07:24.5045995Z   | 
2018-08-23T15:07:24.5060525Z ##[error]Error: failures in local notebook tests
2018-08-23T15:07:24.5300625Z [command]/usr/bin/az account clear
2018-08-23T15:07:25.2852224Z ##[error]Script failed with error: Error: /bin/bash failed with return code: 1
2018-08-23T15:07:25.3308824Z ##[section]Finishing: Main Build

```

**Comment by imatiach-msft** [comment]
@mhamilton723 that's a different PR, that's for the lightGBM version update that fixes the frozen notebook issue when running with quantile regression.  The build here failed when loading the model from string and resetting the training data.  I thought I fixed that test but it looks like there are still some issues I need to look into.  I'm going to try to get the version update working first, I posted an issue here:
https://github.com/Microsoft/LightGBM/issues/1604
I'm not sure if that check is actually necessary.

**Comment by imatiach-msft** [comment]
@terrytangyuan I debugged the code and it looks like the ResetTrainingData method is failing because it expects to have already been initialized with training data previously.
Based on the code here it looks like you are supposed to create both boosters, one from string and one from data, and then merge them:
https://github.com/Microsoft/LightGBM/blob/941068eea83175ad4e967361d7f0c6a1daa59e34/python-package/lightgbm/basic.py#L1360

**Comment by imatiach-msft** [comment]
when debugging the native code, it looks like it is failing here:
https://github.com/Microsoft/LightGBM/blob/941068eea83175ad4e967361d7f0c6a1daa59e34/src/boosting/gbdt.cpp#L731

**Comment by imatiach-msft** [comment]
@mhamilton723 would you be able to merge?  The error was fixed.

**Comment by terrytangyuan** [comment]
@imatiach-msft Thanks for the fixes! I'll test this patch internally soon.

**Pull request merged**
