### PR TITLE
Bump to spark3

### PR DESCRIPTION
**Pull request by mhamilton723**

### CODE REVIEW

**Comment by yosit** [comment]
Hi, any chance we can push this forward?

**Comment by javier-recasens** [comment]
Hey @imatiach-msft, how are you doing with this request?

**Comment by yosit** [comment]
There is also this: https://github.com/Azure/mmlspark/pull/726

**Comment by hanbing1587** [comment]
@yosit @mhamilton723 I also got the same errors as yosit when building by sbt. How did you  solve this issue?

**Comment by sam-h-bean** [comment]
When would this be available on Maven? Is it possible to build from Maven today?

**Comment by SamComber** [comment]
Does anyone have any indication as to when this will be available on Maven?

**Comment by juanpaulo** [comment]
Any reason why this was closed without getting merged?

**Pull request closed without merging**
