### PR TITLE
fix: lightgbm binary classifier getting stuck due to single label in some partitions

### PR DESCRIPTION
**Pull request by imatiach-msft**
fix lightgbm binary classifier getting stuck due to single label in some partitions

By default, lightgbm will now fail with exception message instead of timing out with connection refused error when some workers only have a single class and exit early during training.

### CODE REVIEW

**Comment by imatiach-msft** [comment]
closing as this has been fixed with a different PR

**Comment by yinshurman** [comment]
Dose the version 0.18.1 contains the fix?

**Comment by imatiach-msft** [comment]
nope, 0.18.1 does not, the 1.0 version does however

**Pull request closed without merging**
