### PR TITLE
feat: Expose dump model method on MMLSpark-LightGBM so that models can be saved as json.

### PR DESCRIPTION
**Pull request by nur-ag**
Changes needed for:
https://github.com/Azure/mmlspark/issues/720

NOTE: Requires https://github.com/microsoft/LightGBM/pull/2560 to be merged before this, since we will be calling the SWIG function.

EDIT: The PR on the LightGBM repo has been merged, so this should be safe to merge now.

### CODE REVIEW

**Comment by mhamilton723** [comment]
Looks like theres no method called LGBM_BoosterDumpModelSWIG, @imatiach-msft could you advise which method @nur-ag  should use? Thank you!

`[0m[[0m[0minfo[0m] [0m[0mCompiling 184 Scala sources and 1 Java source to /home/vsts/work/1/s/target/scala-2.11/classes ...[0m
[0m[[0m[31merror[0m] [0m[0m/home/vsts/work/1/s/src/main/scala/com/microsoft/ml/spark/lightgbm/LightGBMBooster.scala:116:28: value LGBM_BoosterDumpModelSWIG is not a member of object com.microsoft.ml.lightgbm.lightgbmlib[0m
[0m[[0m[31merror[0m] [0m[0m    val json = lightgbmlib.LGBM_BoosterDumpModelSWIG(boosterPtr, 0, 0, 1, lightgbmlib.new_int64_tp())[0m
[0m[[0m[31merror[0m] [0m[0m                           ^[0m
[0m[[0m[31merror[0m] [0m[0mone error found[0m
[0m[[0m[31merror[0m] [0m[0m(Compile / [31mcompileIncremental[0m) Compilation failed[0m
[0m[[0m[31merror[0m] [0m[0mTotal time: 28 s, completed Dec 1, 2019 7:09:56 PM[0m`

**Comment by imatiach-msft** [comment]
@mhamilton723 actually I need to publish a new lightgbm jar since they added that new method to native code recently

**Comment by mhamilton723** [comment]
> @mhamilton723 actually I need to publish a new lightgbm jar since they added that new method to native code recently

Thanks for the heads up @imatiach-msft, can you poke me when the new jar is up?

**Comment by imatiach-msft** [comment]
@mhamilton723  I've released lightgbm 2.3.150 just now (12/8/19), it should be available on maven.  This PR just needs to update the build.scala.

**Pull request merged**
