### PR TITLE
Added early stopping round to lightGBM

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by mhamilton723** [comment]
Nice work, you have been killing it with these PRs :). Ill merge once the build passes

**Comment by terrytangyuan** [comment]
@mhamilton723 We are adding to our internal ML platform, along with other popular algorithms. 

BTW, build failed but I don't have access to your testing machine as well as the website you linked in the comment.

**Comment by mhamilton723** [comment]
@terrytangyuan What group/company are you working with?

and it looks like a compile error:

```
2018-07-12T18:41:12.9359640Z Compiling 11 Scala sources to $HOME/agent/_work/4/s/src/lightgbm/target/scala-2.11/classes ...
2018-07-12T18:41:14.4604400Z ##[error]$HOME/agent/_work/4/s/src/lightgbm/src/main/scala/TrainParams.scala:35:12: class ClassifierTrainParams needs to be abstract, since method earlyStoppingRound in class TrainParams of type => Int is not defined
2018-07-12T18:41:14.4621210Z ##[error]case class ClassifierTrainParams(val parallelism: String, val numIterations: Int, val learningRate: Double,
2018-07-12T18:41:14.4635870Z ##[error]^
2018-07-12T18:41:14.4651440Z ##[error]$HOME/agent/_work/4/s/src/lightgbm/src/main/scala/TrainParams.scala:47:12: class RegressorTrainParams needs to be abstract, since method earlyStoppingRound in class TrainParams of type => Int is not defined
2018-07-12T18:41:14.4667630Z ##[error]case class RegressorTrainParams(val parallelism: String, val numIterations: Int, val learningRate: Double,
2018-07-12T18:41:14.4682320Z ##[error]^
2018-07-12T18:41:14.4728620Z ##[error]two errors found
2018-07-12T18:41:20.2513880Z Compiling 1 Scala source to $HOME/agent/_work/4/s/src/train-classifier/target/scala-2.11/classes ...
2018-07-12T18:41:21.3398420Z Done compiling.
2018-07-12T18:41:27.1500720Z Compiling 1 Scala source to $HOME/agent/_work/4/s/src/train-regressor/target/scala-2.11/classes ...
2018-07-12T18:41:28.0183250Z Done compiling.
2018-07-12T18:41:34.5884310Z Compiling 2 Scala sources to $HOME/agent/_work/4/s/src/image-transformer/target/scala-2.11/classes ...
2018-07-12T18:41:36.0928890Z Done compiling.
2018-07-12T18:41:41.9765420Z Compiling 1 Scala source to $HOME/agent/_work/4/s/src/compute-per-instance-statistics/target/scala-2.11/classes ...
2018-07-12T18:41:42.8086600Z Done compiling.
2018-07-12T18:41:49.2319940Z Compiling 1 Scala source to $HOME/agent/_work/4/s/src/compute-model-statistics/target/scala-2.11/classes ...
2018-07-12T18:41:51.0133160Z Done compiling.
2018-07-12T18:41:56.6192410Z Compiling 4 Scala sources to $HOME/agent/_work/4/s/src/cntk-model/target/scala-2.11/classes ...
2018-07-12T18:41:58.9850280Z Done compiling.
2018-07-12T18:42:04.8233420Z Compiling 2 Scala sources to $HOME/agent/_work/4/s/src/find-best-model/target/scala-2.11/classes ...
2018-07-12T18:42:05.9115000Z Done compiling.
2018-07-12T18:42:12.2952070Z Compiling 2 Scala sources to $HOME/agent/_work/4/s/src/image-featurizer/target/scala-2.11/classes ...
2018-07-12T18:42:13.0605450Z Done compiling.
2018-07-12T18:42:19.8881980Z Compiling 5 Scala sources to $HOME/agent/_work/4/s/src/cntk-train/target/scala-2.11/classes ...
2018-07-12T18:42:22.1022820Z Done compiling.
2018-07-12T18:42:27.4365520Z Compiling 4 Scala sources to $HOME/agent/_work/4/s/src/tune-hyperparameters/target/scala-2.11/classes ...
2018-07-12T18:42:28.9438040Z Done compiling.
2018-07-12T18:42:40.1158550Z ##[error](lightgbm / Compile / compileIncremental) Compilation failed
2018-07-12T18:42:40.1308470Z ##[error]Total time: 335 s, completed Jul 12, 2018 6:42:40 PM
2018-07-12T18:42:40.3596650Z ##[error]Error: failure when running sbt -no-colors full-build
2018-07-12T18:42:40.3820150Z [command]/usr/bin/az account clear
2018-07-12T18:42:41.2134270Z ##[error]Script failed with error: Error: /bin/bash failed with return code: 1
```

**Comment by terrytangyuan** [comment]
@mhamilton723 I am in the same team with @ywskycn at Ant Financial.

**Comment by terrytangyuan** [comment]
@mhamilton723 Seems like the build is stuck?

**Comment by mhamilton723** [comment]
@terrytangyuan our build isnt set up to automatically test every PR, we manually queue it for security purposes. Ill queue yours up now!

**Comment by terrytangyuan** [comment]
@mhamilton723 Thanks! We are using it on our own infra. BTW, I sent you guys an email regarding another issue/feature request.

**Comment by mhamilton723** [comment]
looks like another compile error

```
2018-07-13T16:08:45.6037650Z Done compiling.
2018-07-13T16:08:51.6589570Z Compiling 11 Scala sources to $HOME/agent/_work/4/s/src/lightgbm/target/scala-2.11/classes ...
2018-07-13T16:08:52.4565570Z ##[error]$HOME/agent/_work/4/s/src/lightgbm/src/main/scala/LightGBMClassifier.scala:51:44: not enough arguments for method apply: (parallelism: String, numIterations: Int, learningRate: Double, numLeaves: Int, maxBin: Int, baggingFraction: Double, baggingFreq: Int, baggingSeed: Int, earlyStoppingRound: Int, featureFraction: Double, maxDepth: Int, minSumHessianInLeaf: Double, numMachines: Int)com.microsoft.ml.spark.ClassifierTrainParams in object ClassifierTrainParams.
2018-07-13T16:08:52.4584100Z ##[error]Unspecified value parameter numMachines.
2018-07-13T16:08:52.4599180Z ##[error]val trainParams = ClassifierTrainParams(getParallelism, getNumIterations, getLearningRate, getNumLeaves,
2018-07-13T16:08:52.4614260Z ##[error]^
2018-07-13T16:08:52.5611470Z ##[error]$HOME/agent/_work/4/s/src/lightgbm/src/main/scala/LightGBMRegressor.scala:74:43: not enough arguments for method apply: (parallelism: String, numIterations: Int, learningRate: Double, numLeaves: Int, application: String, alpha: Double, maxBin: Int, baggingFraction: Double, baggingFreq: Int, baggingSeed: Int, earlyStoppingRound: Int, featureFraction: Double, maxDepth: Int, minSumHessianInLeaf: Double, numMachines: Int)com.microsoft.ml.spark.RegressorTrainParams in object RegressorTrainParams.
2018-07-13T16:08:52.5631530Z ##[error]Unspecified value parameter numMachines.
2018-07-13T16:08:52.5647020Z ##[error]val trainParams = RegressorTrainParams(getParallelism, getNumIterations, getLearningRate, getNumLeaves,
2018-07-13T16:08:52.5661780Z ##[error]^
2018-07-13T16:08:53.1384640Z ##[error]two errors found
```

**Comment by terrytangyuan** [comment]
My apologies. Thought this was a simple addition so I just edited on Github. Should be fixed now.

**Comment by mhamilton723** [comment]
Hey @terrytangyuan could you rebase this onto master and squash the changes into a single commit with the first commit message? Thanks!

**Comment by terrytangyuan** [comment]
Done!

**Pull request merged**
