### PR TITLE
Remove LightGBMBooster's mergeModels function

### PR DESCRIPTION
**Pull request by ywskycn**
Discussed in https://github.com/Azure/mmlspark/issues/315, the merge function doesn't need anymore. Would better to remove it.

### CODE REVIEW

**Comment by ywskycn** [comment]
@imatiach-msft @mhamilton723 know how to make the build-pr happy? :)

**Comment by imatiach-msft** [comment]
@ywskycn yes, sorry, there was a major refactor that @mhamilton723 recently did to use Azure Databricks cluster for our tests instead of HDInsight and now it looks like the e2e builds are getting stuck, he is looking into it.  The PR will be checked in as soon as the build issue is resolved, sorry for the inconvenience.

**Comment by mhamilton723** [comment]
Sorry @ywskycn this is not your issue and I will check this in as soon as I iron out the build kinks, hopefully by tomorrow. If this is a blocker please let us know

**Comment by mhamilton723** [comment]
@ywskycn could you quickly rebase your changes on latest master so we can push it through the new build? Thanks!

**Pull request merged**
