### PR TITLE
LightGBMRegressor.py : updating imports

### PR DESCRIPTION
**Pull request by JeanLescut**
SparkContext was imported twice. Also SQLContext is outdated, and was not used anyways
... or did I miss something ?

### CODE REVIEW

**Review by imatiach-msft — APPROVED** [review]
LGTM!

**Comment by mhamilton723** [comment]
@imatiach-msft sorry for the pain had to reconf the build as azure devops had an outage that broke us

**Comment by imatiach-msft** [comment]
closing as this issue has been fixed in PR:
https://github.com/Azure/mmlspark/pull/758

**Pull request closed without merging**
