### PR TITLE
Adding parameters to lightGBM classifier and regressor.

### PR DESCRIPTION
**Pull request by katerinagl**
These parameters were added:
maxBin, baggingFraction, baggingFreq, baggingSeed, featureFraction, maxDepth, minSumHessianInLeaf

### CODE REVIEW

**Comment by imatiach-msft** [comment]
It looks like there are just some minor style issues - the line length needs to be below 120 chars

**Comment by imatiach-msft** [comment]
I've fixed some minor style issues, running a new build

**Comment by imatiach-msft** [comment]
I've updated the default values for the params to be same as the defaults in LightGBM here:
https://github.com/Microsoft/LightGBM/blob/master/docs/Parameters.rst

**Comment by katerinagl** [comment]
seems I don't have access to build results... so i can't fix it, sorry

**Comment by katerinagl** [comment]
ok, thank you very much :)

**Pull request merged**
