### PR TITLE
Add column name to UnsupportedOperationException for clarity

### PR DESCRIPTION
**Pull request by jwgwalton**
Hi @imatiach-msft and @mhamilton723 , Sorry I messed up merging the changes from master and then squashing it so just opened this.

### CODE REVIEW

**Comment by jwgwalton** [comment]
Previous pull request was #532

**Comment by imatiach-msft** [comment]
@jwgwalton seem to be getting this error now:

##[error]$HOME/agent/_work/1/s/src/value-indexer/src/main/scala/ValueIndexer.scala:65:50: not enough arguments for method apply: (index: Int)Char in class StringOps.
##[error]Unspecified value parameter index.
##[error]val column = dataset.schema(getInputCol).name()
##[error]^
##[error]one error found

**Comment by imatiach-msft** [comment]
@jwgwalton it looks like name is a property and not a function, so you just need to remove the parentheses

**Comment by jwgwalton** [comment]
Cheers @imatiach-msft i'll get there eventually

**Comment by imatiach-msft** [comment]
@jwgwalton actually, why not just use getInputCol instead?  That's already the column name as a string.

**Pull request merged**
