### PR TITLE
build: Cross-compile to Scala 2.12

### PR DESCRIPTION
**Pull request by nightscape**
Done:

- SBT file adapted for cross-compilation
- Ambiguities due to [Scala 2.12 SAM ambiguity](https://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#sam-conversion) resolved.

To Do:

- Make tests succeed
- Test doc generation

### CODE REVIEW

**Comment by nightscape** [comment]
@drdarshan @mhamilton723 a lot of tests are failing because there seem to be missing datasets, possibly/probably caused by this
```
ERROR: The subscription of 'ce1dee05-8cf6-4ad6-990a-9c80868800ba' doesn't exist in cloud 'AzureCloud'.
```
I assume this subscription requires permissions to log in and retrieve the datasets, correct?
If so, is there a way I can get the datasets to test locally, or do you have to test this in your environment?

**Comment by mhamilton723** [comment]
Hey @nightscape thanks so much for this great PR. 

Datasets can be downloaded from 
https://mmlspark.blob.core.windows.net/installers/datasets-2019-05-02.tgz

**Comment by nightscape** [comment]
Hi @mhamilton723, I had a look at the errors in the build, but at first glance I don’t see how they could be caused by the Scala 2.12 switch.
Unfortunately, I’ve been pulled into other topics and can’t spend much more time on this.
Would it be ok to chicken out here?

**Comment by mhamilton723** [comment]
@nightscape, appreciate you taking it this far. Just rebased on top of some latest test flakiness ixes so well see how it goes :)

**Comment by nightscape** [comment]
For some reason, Github didn't pick up the changes I made to my branch.
Possibly caused by the recent hickups: https://www.githubstatus.com/
Will try changing something and force-pushing again.

**Comment by nightscape** [comment]
@imatiach-msft, the build seems stuck...
Could you trigger it again?
Thank you!

**Comment by imatiach-msft** [comment]
done!

**Comment by nightscape** [comment]
@imatiach-msft the build seems to have failed?
Unfortunately I can't see the exact error, only that `/bin/bash` exited with status 1 which is not very helpful...

**Comment by imatiach-msft** [comment]
sorry let me rerun and then I will report the error.  The devops project really needs to be made public as this is unsustainable, external devs need to be able to see the errors... tagging @mhamilton723 .

**Comment by imatiach-msft** [comment]
wow I see tons of build failures everywhere lol
[scala_2.12_build_log.txt](https://github.com/Azure/mmlspark/files/4524579/scala_2.12_build_log.txt)

**Comment by imatiach-msft** [comment]
seems like a bunch of our dependencies don't have 2.12 versions yet?

**Comment by nightscape** [comment]
@imatiach-msft right. I assume this is a new dependency, afair I had this branch compiling locally before I rebased on master.
Will try to get a 2.12 build for https://github.com/linkedin/isolation-forest

**Comment by nightscape** [comment]
Askes for a 2.12 build here: https://github.com/linkedin/isolation-forest/issues/14

**Comment by imatiach-msft** [comment]
also adding @eisber  for the isolation forest dependency

**Comment by imatiach-msft** [comment]
I wonder if there is some way to make this an optional dependency for now for scala 2.12 build...

**Comment by eisber** [comment]
@jverbus should be able to help with the dependency. he built the artifacts for spark 2.3.0 vs 2.4.3

**Comment by nightscape** [comment]
@imatiach-msft @eisber I updated to the newly released isolation-forest version for Scala 2.12 (thanks @jverbus !) and rebased on master.
Unfortunately, I don't see any results from the CI run. Does that have to be triggered manually?

**Comment by nightscape** [comment]
@eisber unfortunately I still don't see the exact error in the Azure pipeline.
Would you be so kind to paste the relevant parts here?
Thank you!

**Comment by eisber** [comment]
sorry for the long delay... 

Info Provided - Suite ClassBalancerSuite took 4.357s
[info] - yield proper weights
[info] + Test yield proper weights took 0.844s 
Info Provided - Shutting down spark session
[info] CacherSuite:
20/06/04 12:10:09 WARN CacheManager: Asked to cache already cached data.
20/06/04 12:10:10 WARN CacheManager: Asked to cache already cached data.
20/06/04 12:10:10 WARN CacheManager: Asked to cache already cached data.
[info] - Serialization Fuzzing
[info]   + Creating a spark session for suite CacherSuite 
[info] + Test Serialization Fuzzing took 0.416s 
20/06/04 12:10:10 WARN CacheManager: Asked to cache already cached data.
[info] - Experiment Fuzzing
[info] + Test Experiment Fuzzing took 0.002s 
20/06/04 12:10:10 WARN CacheManager: Asked to cache already cached data.
[info] - Be the identity operation
[info] + Test Be the identity operation took 0.027s 
Info Provided - Suite CacherSuite took 0.445s
Info Provided - Shutting down spark session
[info] SummarizeDataSuite:
20/06/04 12:10:10 WARN Utils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.debug.maxToStringFields' in SparkEnv.conf.
[info] - Serialization Fuzzing
[info]   + Creating a spark session for suite SummarizeDataSuite 
[info] + Test Serialization Fuzzing took 7.856s 
[info] - Experiment Fuzzing
[info] + Test Experiment Fuzzing took 1.413s 
[info] - Smoke test for summarizing basic DF - schema transform
[info] + Test Smoke test for summarizing basic DF - schema transform took 0.017s 
[info] - Smoke test for summary params
[info] + Test Smoke test for summary params took 0.007s 
[info] - Smoke test for summarizing basic DF
[info] + Test Smoke test for summarizing basic DF took 1.611s 
[info] - Smoke test for summarizing missings DF
[info] + Test Smoke test for summarizing missings DF took 1.552s 
[info] - Smoke test for subset summarizing missings DF
[info] + Test Smoke test for subset summarizing missings DF took 0.47s 
Alert Provided - Suite SummarizeDataSuite took 12.926s
Info Provided - Shutting down spark session
[info] RepartitionSuite:
[info] - Serialization Fuzzing
[info]   + Creating a spark session for suite RepartitionSuite 
[info] + Test Serialization Fuzzing took 0.389s 
[info] - Experiment Fuzzing
[info] + Test Experiment Fuzzing took 0.002s 
[info] - Work for several values of n
[info] + Test Work for several values of n took 0.058s 
[info] - Should allow a user to set the partitions specifically in pipeline transform
[info] + Test Should allow a user to set the partitions specifically in pipeline transform took 0.058s 
Info Provided - Suite RepartitionSuite took 0.507s
Info Provided - Shutting down spark session
[info] BatchIteratorSuite:
ratio: 1.0039155890709441, Batched: 2338ms, normal: 2329ms



[error] Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[error] OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/mml-natives8324893102437100607/libopencv_java320.so which might have disabled stack guard. The VM will try to fix the stack guard now.
[error] It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
[info] Could not generate getters and setters for class com.microsoft.ml.spark.automl.BestModel due to no default constructor
[info] Could not generate getters and setters for class com.microsoft.ml.spark.automl.TuneHyperparametersModel due to no default constructor
[info] Could not generate getters and setters for class com.microsoft.ml.spark.featurize.AssembleFeaturesModel due to no default constructor
[info] Could not generate getters and setters for class com.microsoft.ml.spark.featurize.CleanMissingDataModel due to no default constructor
[info] Could not generate getters and setters for class org.apache.spark.ml.PipelineModel due to no default constructor
[info] Could not generate getters and setters for class com.microsoft.ml.spark.featurize.text.TextFeaturizerModel due to no default constructor
[info] Could not generate getters and setters for class com.microsoft.ml.spark.isolationforest.IsolationForestModel due to no default constructor
[info] Could not generate getters and setters for class com.microsoft.ml.spark.lightgbm.LightGBMClassificationModel due to no default constructor
[info] Could not generate getters and setters for class com.microsoft.ml.spark.lightgbm.LightGBMRankerModel due to no default constructor
[info] Could not generate getters and setters for class com.microsoft.ml.spark.lightgbm.LightGBMRegressionModel due to no default constructor
[info] Could not generate getters and setters for class org.apache.spark.ml.PipelineModel due to no default constructor
[info] Could not generate getters and setters for class com.microsoft.ml.spark.stages.TimerModel due to no default constructor
[info] Could not generate getters and setters for class com.microsoft.ml.spark.train.TrainedClassifierModel due to no default constructor
[info] Could not generate getters and setters for class com.microsoft.ml.spark.train.TrainedRegressorModel due to no default constructor

**Comment by nightscape** [comment]
Hmm, the only errors I see are the ones about OpenCV:
```
[error] Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[error] OpenJDK 64-Bit Server VM warning: You have loaded library /tmp/mml-natives8324893102437100607/libopencv_java320.so which might have disabled stack guard. The VM will try to fix the stack guard now.
[error] It's highly recommended that you fix the library with 'execstack -c ', or link it with '-z noexecstack'.
```

I honestly don't have any clue what to do with them.
Could anyone from the Azure team take it from here?

**Comment by utsavavlino** [comment]
@mhamilton723 any inputs on the status , will there be 2.12 support for mmlspark soon?

**Comment by yosit** [comment]
Any chance to push this forward?

**Comment by yosit** [comment]
@nightscape a small fix to your branch would be to:
sed -i 's/scala-2\.11/scala-2.12/' src/it/scala/com/microsoft/ml/spark/codegen/CodegenConfig.scala

**Comment by nightscape** [comment]
Overall I think this needs to be pushed over the line by someone from the Azure team like @eisber, @imatiach-msft or @mhamilton723.
If someone from the Azure team tells me "Look, make these 3 changes and we'll take it from there", I'd be happy to.
But right now I won't invest more time until there is a commitment to actually get this merged.

**Comment by yosit** [comment]
@nightscape Thank you for your contribution!

@eisber , @imatiach-msft , @mhamilton723  - We have been using this successfully at ZipRecruiter.
Happy to see this small changes merged.

**Comment by hanbing1587** [comment]
@nightscape  I try to use "sbt clean package" to build mmlspark from this branch and generate a jar file. But I can't use the python API for lightgbm. The error information is "ModuleNotFoundError: No module named 'mmlspark.lightgbm._LightGBMClassifier' ". I estimate my building command is not correct. So what is the correct command to build mmlspark with python API.

**Comment by nightscape** [comment]
@hanbing1587 unfortunately I don't know either...
I just changed the Scala version settings and fixed all compile errors.

**Comment by juanpaulo** [comment]
related to #912?

**Comment by nightscape** [comment]
Definitely. I have no idea why the other PR got closed though, or why this one doesn't receive any love...
The Open Source part of this repo leaves room for improvement :stuck_out_tongue_closed_eyes:

**Comment by imatiach-msft** [comment]
closing as we already support scala 2.12

**Pull request closed without merging**
