### PR TITLE
Add Medical Entity extraction Notebook

### PR DESCRIPTION
**Pull request by mhamilton723**
- also fix the CNTKmodel setOutputINodendex

### CODE REVIEW

**Comment by rastala** [comment]
Could you add a source attribution for the example text. I think it's from this article: 
http://acrabstracts.org/abstract/baricitinib-methotrexate-or-baricitinib-plus-methotrexate-in-patients-with-early-rheumatoid-arthritis-who-had-received-limited-or-no-treatment-with-disease-modifying-anti-rheumatic-drugs-dmards-p/

**Comment by rastala** [comment]
Also, please add more verbiage about what's the problem that's being solved, and what's happening at each step. Here's a good example to follow:
https://github.com/Microsoft/CNTK/blob/master/Tutorials/CNTK_202_Language_Understanding.ipynb

**Comment by mhamilton723** [comment]
Yes, do I need to rebuild to do that or is there some slick way to avoid it?

**Comment by elibarzilay** [comment]
@mhamilton723, build fails in the e2e tests/

**Pull request merged**
